ERROR:root:Traceback (most recent call last):
  File "C:\Users\akzm0\OneDrive\πŸ≈¡ »≠∏È\CHaser\main_chaser.py", line 162, in main
    for i in ExitList:
TypeError: 'NoneType' object is not iterable

