ERROR:root:Traceback (most recent call last):
  File "C:\Users\akzm0\OneDrive\πŸ≈¡ »≠∏È\CHaser\main_chaser.py", line 592, in main
    if ExitRoof2[i] == ExitRoof2[i+2]:
IndexError: list index out of range

